"""change content to content_url to chapter

Revision ID: 11bfa86eb501
Revises: 9c0922f79a9f
Create Date: 2025-11-07 17:17:57.925729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11bfa86eb501'
down_revision = '9c0922f79a9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('content_url', sa.String(length=500), nullable=True))
    op.drop_column('chapters', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapters', sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('chapters', 'content_url')
    # ### end Alembic commands ###
