"""add_deleted_at_to_agent_sessions

Revision ID: 457aceb35eb0
Revises: 76245c420679
Create Date: 2026-01-30 16:23:34.166356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '457aceb35eb0'
down_revision = '76245c420679'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_sessions', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='软删除时间'))
    op.alter_column('agent_sessions', 'creation_uuid',
               existing_type=sa.UUID(),
               comment='关联的创作项目 UUID',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.alter_column('agent_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               comment='会话所属用户 ID',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment='会话状态: active, reset, completed',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.drop_index(op.f('idx_agent_sessions_creation_uuid'), table_name='agent_sessions')
    op.drop_index(op.f('idx_agent_sessions_status'), table_name='agent_sessions')
    op.drop_index(op.f('idx_agent_sessions_user_id'), table_name='agent_sessions')
    op.create_index(op.f('ix_agent_sessions_creation_uuid'), 'agent_sessions', ['creation_uuid'], unique=False)
    op.create_index(op.f('ix_agent_sessions_status'), 'agent_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_foreign_key(None, 'agent_sessions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_shots_creation_id'), table_name='shots')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_shots_creation_id'), 'shots', ['creation_id'], unique=False)
    op.drop_constraint(None, 'agent_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_agent_sessions_user_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_status'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_creation_uuid'), table_name='agent_sessions')
    op.create_index(op.f('idx_agent_sessions_user_id'), 'agent_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_agent_sessions_status'), 'agent_sessions', ['status'], unique=False)
    op.create_index(op.f('idx_agent_sessions_creation_uuid'), 'agent_sessions', ['creation_uuid'], unique=False)
    op.alter_column('agent_sessions', 'status',
               existing_type=sa.VARCHAR(length=20),
               comment=None,
               existing_comment='会话状态: active, reset, completed',
               existing_nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('agent_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='会话所属用户 ID',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('agent_sessions', 'creation_uuid',
               existing_type=sa.UUID(),
               comment=None,
               existing_comment='关联的创作项目 UUID',
               existing_nullable=False,
               existing_server_default=sa.text('gen_random_uuid()'))
    op.drop_column('agent_sessions', 'deleted_at')
    # ### end Alembic commands ###
