"""Add Agent workflow support

Revision ID: 47a3c98a9ad3
Revises: 1767578870_scene
Create Date: 2026-01-28 11:43:00.121183

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47a3c98a9ad3'
down_revision = '1767578870_scene'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # 手动创建 PostgreSQL ENUM 类型（Alembic autogenerate 不会自动创建）
    # PostgreSQL CREATE TYPE 不支持 IF NOT EXISTS，需要先检查再创建
    # 注意：pg_type 中的 typname 是小写的
    from sqlalchemy import text
    conn = op.get_bind()

    # 检查并创建 workflow_mode_enum
    result = conn.execute(text("SELECT 1 FROM pg_type WHERE typname = 'workflow_mode_enum'"))
    if result.scalar() is None:
        op.execute("CREATE TYPE workflow_mode_enum AS ENUM ('TRADITIONAL', 'AGENT')")

    # 检查并创建 production_stage_enum
    result = conn.execute(text("SELECT 1 FROM pg_type WHERE typname = 'production_stage_enum'"))
    if result.scalar() is None:
        op.execute("CREATE TYPE production_stage_enum AS ENUM ('INIT', 'SCRIPT_ANALYSIS', 'ASSET_GENERATION', 'STORYBOARD_CREATION', 'AUDIO_PROCESSING', 'EDITING', 'COMPLETED')")

    # 检查并创建 checkpoint_status_enum
    result = conn.execute(text("SELECT 1 FROM pg_type WHERE typname = 'checkpoint_status_enum'"))
    if result.scalar() is None:
        op.execute("CREATE TYPE checkpoint_status_enum AS ENUM ('PENDING', 'APPROVED', 'REJECTED', 'PARTIAL')")

    # 检查并创建 message_role_enum
    result = conn.execute(text("SELECT 1 FROM pg_type WHERE typname = 'message_role_enum'"))
    if result.scalar() is None:
        op.execute("CREATE TYPE message_role_enum AS ENUM ('USER', 'ASSISTANT', 'SYSTEM')")

    # 检查并创建 event_type_enum
    result = conn.execute(text("SELECT 1 FROM pg_type WHERE typname = 'event_type_enum'"))
    if result.scalar() is None:
        op.execute("CREATE TYPE event_type_enum AS ENUM ('MESSAGE', 'TOOL_CALL', 'TOOL_OUTPUT', 'PROGRESS', 'BOARD_ACTION', 'ACTION_REQUEST', 'THINKING', 'ERROR')")

    op.create_table('agent_checkpoints',
    sa.Column('thread_id', sa.String(length=255), nullable=False, comment='LangGraph 执行图的 thread_id，对应 creation.uuid'),
    sa.Column('checkpoint_id', sa.String(length=255), nullable=False, comment='检查点唯一标识符'),
    sa.Column('parent_checkpoint_id', sa.String(length=255), nullable=True, comment='父检查点 ID，用于追踪检查点链'),
    sa.Column('checkpoint_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='完整的 ComicDramaState 数据，包含 characters, scenes, storyboards 等'),
    sa.Column('checkpoint_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='检查点元数据，如节点名称、执行步数、时间戳等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='检查点创建时间'),
    sa.PrimaryKeyConstraint('thread_id')
    )
    op.create_index('idx_checkpoint_created_at', 'agent_checkpoints', ['created_at'], unique=False)
    op.create_index('idx_checkpoint_id', 'agent_checkpoints', ['checkpoint_id'], unique=False)
    op.create_index('idx_checkpoint_thread_created', 'agent_checkpoints', ['thread_id', 'created_at'], unique=False)
    op.create_index('idx_checkpoint_thread_id', 'agent_checkpoints', ['thread_id'], unique=False)
    op.create_index(op.f('ix_agent_checkpoints_checkpoint_id'), 'agent_checkpoints', ['checkpoint_id'], unique=False)
    op.create_index(op.f('ix_agent_checkpoints_created_at'), 'agent_checkpoints', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_checkpoints_thread_id'), 'agent_checkpoints', ['thread_id'], unique=False)
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='会话唯一标识符'),
    sa.Column('creation_id', sa.Integer(), nullable=False, comment='关联的创作项目 ID'),
    sa.Column('thread_id', sa.String(length=100), nullable=False, comment='LangGraph 执行图的 thread_id，用于断点恢复'),
    sa.Column('current_stage', postgresql.ENUM('INIT', 'SCRIPT_ANALYSIS', 'ASSET_GENERATION', 'STORYBOARD_CREATION', 'AUDIO_PROCESSING', 'EDITING', 'COMPLETED', name='production_stage_enum', create_type=False), nullable=False, comment='当前创作阶段'),
    sa.Column('checkpoint_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='当前检查点的数据，如解析结果、生成的资产等'),
    sa.Column('user_feedback', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='用户在检查点的反馈数据'),
    sa.Column('checkpoint_status', postgresql.ENUM('PENDING', 'APPROVED', 'REJECTED', 'PARTIAL', name='checkpoint_status_enum', create_type=False), nullable=True, comment='当前检查点的状态'),
    sa.Column('session_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='会话元数据，如使用的模型、配置等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='会话完成时间'),
    sa.ForeignKeyConstraint(['creation_id'], ['creations.creation_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_index(op.f('ix_agent_sessions_creation_id'), 'agent_sessions', ['creation_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_current_stage'), 'agent_sessions', ['current_stage'], unique=False)
    op.create_index(op.f('ix_agent_sessions_session_id'), 'agent_sessions', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_sessions_thread_id'), 'agent_sessions', ['thread_id'], unique=True)
    op.create_index(op.f('ix_agent_sessions_uuid'), 'agent_sessions', ['uuid'], unique=True)
    op.create_table('agent_messages',
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(as_uuid=False), server_default=sa.text('gen_random_uuid()'), nullable=False, comment='消息唯一标识符'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='关联的 Agent 会话 ID'),
    sa.Column('role', postgresql.ENUM('USER', 'ASSISTANT', 'SYSTEM', name='message_role_enum', create_type=False), nullable=False, comment='消息角色：user/assistant/system'),
    sa.Column('content', sa.Text(), nullable=True, comment='消息文本内容'),
    sa.Column('event_type', postgresql.ENUM('MESSAGE', 'TOOL_CALL', 'TOOL_OUTPUT', 'PROGRESS', 'BOARD_ACTION', 'ACTION_REQUEST', 'THINKING', 'ERROR', name='event_type_enum', create_type=False), nullable=False, comment='事件类型，用于区分不同的 SSE 事件'),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='消息元数据，如工具调用参数、进度详情、看板操作等'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_agent_messages_created_at'), 'agent_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_messages_event_type'), 'agent_messages', ['event_type'], unique=False)
    op.create_index(op.f('ix_agent_messages_message_id'), 'agent_messages', ['message_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_role'), 'agent_messages', ['role'], unique=False)
    op.create_index(op.f('ix_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_messages_uuid'), 'agent_messages', ['uuid'], unique=True)
    op.alter_column('assets', 'duration',
               existing_type=sa.INTEGER(),
               comment='时长(毫秒),仅音频/视频',
               existing_comment='时长(秒),仅音频/视频',
               existing_nullable=True)
    # 先添加可为空的列，更新现有数据后再改为非空
    op.add_column('creations', sa.Column('workflow_mode', postgresql.ENUM('TRADITIONAL', 'AGENT', name='workflow_mode_enum', create_type=False), nullable=True, comment='工作流模式：traditional=传统手动工作流（Celery），agent=Agent智能协助工作流（LangGraph）'))
    # 为现有数据设置默认值 'TRADITIONAL'
    op.execute("UPDATE creations SET workflow_mode = 'TRADITIONAL' WHERE workflow_mode IS NULL")
    # 修改为不允许为空
    op.alter_column('creations', 'workflow_mode',
               existing_type=postgresql.ENUM('TRADITIONAL', 'AGENT', name='workflow_mode_enum', create_type=False),
               nullable=False)
    op.add_column('creations', sa.Column('agent_session_id', sa.String(length=100), nullable=True, comment='关联的 Agent 会话 ID（仅 workflow_mode=agent 时有效）'))
    op.create_index(op.f('ix_creations_agent_session_id'), 'creations', ['agent_session_id'], unique=False)
    op.create_index(op.f('ix_creations_workflow_mode'), 'creations', ['workflow_mode'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creations_workflow_mode'), table_name='creations')
    op.drop_index(op.f('ix_creations_agent_session_id'), table_name='creations')
    op.drop_column('creations', 'agent_session_id')
    op.drop_column('creations', 'workflow_mode')
    op.alter_column('assets', 'duration',
               existing_type=sa.INTEGER(),
               comment='时长(秒),仅音频/视频',
               existing_comment='时长(毫秒),仅音频/视频',
               existing_nullable=True)
    op.drop_index(op.f('ix_agent_messages_uuid'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_session_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_role'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_message_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_event_type'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_created_at'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index(op.f('ix_agent_sessions_uuid'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_thread_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_session_id'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_current_stage'), table_name='agent_sessions')
    op.drop_index(op.f('ix_agent_sessions_creation_id'), table_name='agent_sessions')
    op.drop_table('agent_sessions')
    op.drop_index(op.f('ix_agent_checkpoints_thread_id'), table_name='agent_checkpoints')
    op.drop_index(op.f('ix_agent_checkpoints_created_at'), table_name='agent_checkpoints')
    op.drop_index(op.f('ix_agent_checkpoints_checkpoint_id'), table_name='agent_checkpoints')
    op.drop_index('idx_checkpoint_thread_id', table_name='agent_checkpoints')
    op.drop_index('idx_checkpoint_thread_created', table_name='agent_checkpoints')
    op.drop_index('idx_checkpoint_id', table_name='agent_checkpoints')
    op.drop_index('idx_checkpoint_created_at', table_name='agent_checkpoints')
    op.drop_table('agent_checkpoints')
    # ### end Alembic commands ###
