"""Add current_task_id column to creations

Revision ID: 687f8945056a
Revises: d3b6408baef4
Create Date: 2025-11-12 15:17:03.674686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '687f8945056a'
down_revision = 'd3b6408baef4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
