"""update charac tags type

Revision ID: 87258fab8d0b
Revises: 9ddb734191a3
Create Date: 2025-11-18 15:31:10.436011

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ARRAY


# revision identifiers, used by Alembic.
revision = '87258fab8d0b'
down_revision = '9ddb734191a3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 将 TEXT 转换为 ARRAY(String)
    # 如果 tags 是 JSON 字符串，需要先解析为数组，然后转换为 PostgreSQL ARRAY
    op.execute("""
        ALTER TABLE characters 
        ALTER COLUMN tags TYPE TEXT[] 
        USING CASE 
            WHEN tags IS NULL THEN NULL
            WHEN tags = '' THEN NULL
            ELSE ARRAY(SELECT jsonb_array_elements_text(tags::jsonb))
        END
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 将 ARRAY(String) 转换回 TEXT（JSON 格式）
    op.execute("""
        ALTER TABLE characters 
        ALTER COLUMN tags TYPE TEXT 
        USING CASE 
            WHEN tags IS NULL THEN NULL
            ELSE to_json(tags)::text
        END
    """)
    # ### end Alembic commands ###
