"""Add current_task_id column to creations

Revision ID: 9ddb734191a3
Revises: 687f8945056a
Create Date: 2025-11-12 15:17:39.583975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ddb734191a3'
down_revision = '687f8945056a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creations', sa.Column('current_task_id', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_creations_current_task_id'), 'creations', ['current_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_creations_current_task_id'), table_name='creations')
    op.drop_column('creations', 'current_task_id')
    # ### end Alembic commands ###
