"""add voice_description to characters

Revision ID: a75f35aab7d1
Revises: fadb320622f0
Create Date: 2025-12-30 16:47:31.250397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a75f35aab7d1'
down_revision = 'fadb320622f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not op.get_context().connection.execute(sa.text("SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'characters' AND column_name = 'voice_description')")).fetchone()[0]:
        op.add_column('characters', sa.Column('voice_description', sa.String(length=500), nullable=True))
    else:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'voice_description')
    # ### end Alembic commands ###
