"""Initial migration

Revision ID: b1a0f05d6d52
Revises: 
Create Date: 2025-11-06 17:23:48.193685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1a0f05d6d52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # 创建默认用户 (用户名: admin, 密码: admin123)
    # 使用预生成的 bcrypt 哈希值，避免在迁移时调用密码哈希函数
    # 密码: admin123
    default_password_hash = "$2b$12$rvPXWK2BIaRTyjww9q/YYudH5RnYpMj.robIE9vEZZBAZyqeDrYuy"
    op.execute(
        sa.text("""
            INSERT INTO users (username, email, hashed_password)
            SELECT 'admin', 'admin@example.com', :password_hash
            WHERE NOT EXISTS (SELECT 1 FROM users WHERE username = 'admin')
        """).bindparams(password_hash=default_password_hash)
    )
    
    op.create_table('novels',
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('author', sa.String(length=100), nullable=True),
    sa.Column('chapter_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('novel_id')
    )
    op.create_index(op.f('ix_novels_novel_id'), 'novels', ['novel_id'], unique=False)
    op.create_index(op.f('ix_novels_title'), 'novels', ['title'], unique=False)
    op.create_table('chapters',
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('chapter_number', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ),
    sa.PrimaryKeyConstraint('chapter_id')
    )
    op.create_index(op.f('ix_chapters_chapter_id'), 'chapters', ['chapter_id'], unique=False)
    op.create_table('creations',
    sa.Column('creation_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('audio_url', sa.String(length=500), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('novel_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapters.chapter_id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('creation_id')
    )
    op.create_index(op.f('ix_creations_creation_id'), 'creations', ['creation_id'], unique=False)
    op.create_index(op.f('ix_creations_title'), 'creations', ['title'], unique=False)
    op.create_table('characters',
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('basic_info', sa.String(length=500), nullable=True),
    sa.Column('appearance', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('hair', sa.Text(), nullable=True),
    sa.Column('clothing', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('visual_style', sa.String(length=100), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('novel_id', sa.Integer(), nullable=True),
    sa.Column('creation_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creation_id'], ['creations.creation_id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.novel_id'], ),
    sa.PrimaryKeyConstraint('character_id')
    )
    op.create_index(op.f('ix_characters_character_id'), 'characters', ['character_id'], unique=False)
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=False)
    op.create_table('scenes',
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('duration', sa.String(length=20), nullable=True),
    sa.Column('time_setting', sa.String(length=50), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('space_type', sa.String(length=50), nullable=True),
    sa.Column('atmosphere', sa.String(length=100), nullable=True),
    sa.Column('creation_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['creation_id'], ['creations.creation_id'], ),
    sa.PrimaryKeyConstraint('scene_id')
    )
    op.create_index(op.f('ix_scenes_scene_id'), 'scenes', ['scene_id'], unique=False)
    op.create_table('shots',
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('shot_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('narration', sa.Text(), nullable=True),
    sa.Column('image_prompt', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('scene_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['scene_id'], ['scenes.scene_id'], ),
    sa.PrimaryKeyConstraint('shot_id')
    )
    op.create_index(op.f('ix_shots_shot_id'), 'shots', ['shot_id'], unique=False)
    op.create_table('shot_characters',
    sa.Column('shot_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], ),
    sa.ForeignKeyConstraint(['shot_id'], ['shots.shot_id'], ),
    sa.PrimaryKeyConstraint('shot_id', 'character_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shot_characters')
    op.drop_index(op.f('ix_shots_shot_id'), table_name='shots')
    op.drop_table('shots')
    op.drop_index(op.f('ix_scenes_scene_id'), table_name='scenes')
    op.drop_table('scenes')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_index(op.f('ix_characters_character_id'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_creations_title'), table_name='creations')
    op.drop_index(op.f('ix_creations_creation_id'), table_name='creations')
    op.drop_table('creations')
    op.drop_index(op.f('ix_chapters_chapter_id'), table_name='chapters')
    op.drop_table('chapters')
    op.drop_index(op.f('ix_novels_title'), table_name='novels')
    op.drop_index(op.f('ix_novels_novel_id'), table_name='novels')
    op.drop_table('novels')
    # 删除默认用户
    op.execute(sa.text("DELETE FROM users WHERE username = 'admin'"))
    
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
