"""add voice_description to characters

Revision ID: fadb320622f0
Revises: 20251230_add_audio_video_url
Create Date: 2025-12-30 16:41:31.879292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fadb320622f0'
down_revision = '20251230_add_audio_video_url'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    if not op.get_context().connection.execute(sa.text("SELECT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'characters' AND column_name = 'voice_description')")).fetchone()[0]:
        op.add_column('characters', sa.Column('voice_description', sa.String(length=500), nullable=True))
    else:
        pass
    op.alter_column('characters', 'tags',
               existing_type=postgresql.ARRAY(sa.TEXT()),
               type_=postgresql.ARRAY(sa.String()),
               existing_nullable=True)
    op.drop_constraint('creem_payments_creem_checkout_id_key', 'creem_payments', type_='unique')
    op.drop_constraint('creem_payments_order_id_key', 'creem_payments', type_='unique')
    op.drop_constraint('creem_payments_uuid_key', 'creem_payments', type_='unique')
    op.drop_index('ix_creem_payments_order_id', table_name='creem_payments')
    op.create_index(op.f('ix_creem_payments_order_id'), 'creem_payments', ['order_id'], unique=True)
    op.create_index(op.f('ix_creem_payments_creem_transaction_id'), 'creem_payments', ['creem_transaction_id'], unique=False)
    op.drop_constraint('creem_subscriptions_creem_subscription_id_key', 'creem_subscriptions', type_='unique')
    op.drop_constraint('creem_subscriptions_subscription_id_key', 'creem_subscriptions', type_='unique')
    op.drop_constraint('creem_subscriptions_uuid_key', 'creem_subscriptions', type_='unique')
    op.drop_index('ix_creem_subscriptions_subscription_id', table_name='creem_subscriptions')
    op.create_index(op.f('ix_creem_subscriptions_subscription_id'), 'creem_subscriptions', ['subscription_id'], unique=True)
    op.drop_constraint('orders_order_number_key', 'orders', type_='unique')
    op.drop_constraint('orders_uuid_key', 'orders', type_='unique')
    op.drop_constraint('orders_product_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_user_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'products', ['product_id'], ['product_id'])
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['user_id'])
    op.drop_constraint('points_accounts_user_id_key', 'points_accounts', type_='unique')
    op.drop_constraint('products_uuid_key', 'products', type_='unique')
    op.drop_column('shots', 'audio_duration')
    op.drop_constraint('uq_subscription_points_history_subscription_period', 'subscription_points_history', type_='unique')
    op.drop_constraint('subscription_points_history_subscription_id_fkey', 'subscription_points_history', type_='foreignkey')
    op.create_foreign_key(None, 'subscription_points_history', 'subscriptions', ['subscription_id'], ['subscription_id'])
    op.drop_column('subscription_points_history', 'created_at')
    op.alter_column('subscriptions', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_constraint('subscriptions_uuid_key', 'subscriptions', type_='unique')
    op.drop_index('ix_subscriptions_order_id', table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_order_id'), 'subscriptions', ['order_id'], unique=True)
    op.drop_constraint('subscriptions_product_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_user_id_fkey', 'subscriptions', type_='foreignkey')
    op.drop_constraint('subscriptions_order_id_fkey', 'subscriptions', type_='foreignkey')
    op.create_foreign_key(None, 'subscriptions', 'users', ['user_id'], ['user_id'])
    op.create_foreign_key(None, 'subscriptions', 'orders', ['order_id'], ['order_id'])
    op.create_foreign_key(None, 'subscriptions', 'products', ['product_id'], ['product_id'])
    op.drop_constraint('webhook_events_creem_event_id_key', 'webhook_events', type_='unique')
    op.create_index(op.f('ix_webhook_events_creem_event_id'), 'webhook_events', ['creem_event_id'], unique=True)
    op.drop_constraint('wechat_payments_order_id_key', 'wechat_payments', type_='unique')
    op.drop_constraint('wechat_payments_out_trade_no_key', 'wechat_payments', type_='unique')
    op.drop_constraint('wechat_payments_uuid_key', 'wechat_payments', type_='unique')
    op.drop_index('ix_wechat_payments_order_id', table_name='wechat_payments')
    op.create_index(op.f('ix_wechat_payments_order_id'), 'wechat_payments', ['order_id'], unique=True)
    op.drop_constraint('wechat_subscriptions_subscription_id_key', 'wechat_subscriptions', type_='unique')
    op.drop_constraint('wechat_subscriptions_uuid_key', 'wechat_subscriptions', type_='unique')
    op.drop_constraint('wechat_subscriptions_wechat_contract_id_key', 'wechat_subscriptions', type_='unique')
    op.drop_index('ix_wechat_subscriptions_subscription_id', table_name='wechat_subscriptions')
    op.create_index(op.f('ix_wechat_subscriptions_subscription_id'), 'wechat_subscriptions', ['subscription_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'voice_description')
    op.drop_index(op.f('ix_wechat_subscriptions_subscription_id'), table_name='wechat_subscriptions')
    op.create_index(op.f('ix_wechat_subscriptions_subscription_id'), 'wechat_subscriptions', ['subscription_id'], unique=False)
    op.create_unique_constraint(op.f('wechat_subscriptions_wechat_contract_id_key'), 'wechat_subscriptions', ['wechat_contract_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('wechat_subscriptions_uuid_key'), 'wechat_subscriptions', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('wechat_subscriptions_subscription_id_key'), 'wechat_subscriptions', ['subscription_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_wechat_payments_order_id'), table_name='wechat_payments')
    op.create_index(op.f('ix_wechat_payments_order_id'), 'wechat_payments', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('wechat_payments_uuid_key'), 'wechat_payments', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('wechat_payments_out_trade_no_key'), 'wechat_payments', ['out_trade_no'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('wechat_payments_order_id_key'), 'wechat_payments', ['order_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_webhook_events_creem_event_id'), table_name='webhook_events')
    op.create_unique_constraint(op.f('webhook_events_creem_event_id_key'), 'webhook_events', ['creem_event_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.drop_constraint(None, 'subscriptions', type_='foreignkey')
    op.create_foreign_key(op.f('subscriptions_order_id_fkey'), 'subscriptions', 'orders', ['order_id'], ['order_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('subscriptions_user_id_fkey'), 'subscriptions', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('subscriptions_product_id_fkey'), 'subscriptions', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_subscriptions_order_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_order_id'), 'subscriptions', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('subscriptions_uuid_key'), 'subscriptions', ['uuid'], postgresql_nulls_not_distinct=False)
    op.alter_column('subscriptions', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.add_column('subscription_points_history', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'subscription_points_history', type_='foreignkey')
    op.create_foreign_key(op.f('subscription_points_history_subscription_id_fkey'), 'subscription_points_history', 'subscriptions', ['subscription_id'], ['subscription_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_subscription_points_history_subscription_period'), 'subscription_points_history', ['subscription_id', 'period_start'], postgresql_nulls_not_distinct=False)
    op.add_column('shots', sa.Column('audio_duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('products_uuid_key'), 'products', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('points_accounts_user_id_key'), 'points_accounts', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('orders_product_id_fkey'), 'orders', 'products', ['product_id'], ['product_id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('orders_uuid_key'), 'orders', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('orders_order_number_key'), 'orders', ['order_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_creem_subscriptions_subscription_id'), table_name='creem_subscriptions')
    op.create_index(op.f('ix_creem_subscriptions_subscription_id'), 'creem_subscriptions', ['subscription_id'], unique=False)
    op.create_unique_constraint(op.f('creem_subscriptions_uuid_key'), 'creem_subscriptions', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('creem_subscriptions_subscription_id_key'), 'creem_subscriptions', ['subscription_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('creem_subscriptions_creem_subscription_id_key'), 'creem_subscriptions', ['creem_subscription_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_creem_payments_creem_transaction_id'), table_name='creem_payments')
    op.drop_index(op.f('ix_creem_payments_order_id'), table_name='creem_payments')
    op.create_index(op.f('ix_creem_payments_order_id'), 'creem_payments', ['order_id'], unique=False)
    op.create_unique_constraint(op.f('creem_payments_uuid_key'), 'creem_payments', ['uuid'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('creem_payments_order_id_key'), 'creem_payments', ['order_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('creem_payments_creem_checkout_id_key'), 'creem_payments', ['creem_checkout_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('characters', 'tags',
               existing_type=postgresql.ARRAY(sa.String()),
               type_=postgresql.ARRAY(sa.TEXT()),
               existing_nullable=True)
    # ### end Alembic commands ###
